<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jean Maximus C. Cacacho">

<title>Supervised Classification of Diabetes Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Supervised Classification of Diabetes Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jean Maximus C. Cacacho </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The data used to perform this <em>study</em> was obtained from an <a href="https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset">open-access Kaggle data repository</a>. The link to the data repository is:</p>
<p>https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset</p>
<p>The primary objective of this study is to perform a <strong>binary classification task with logistic regression</strong>, identifying diabetic from non-diabetic observations. Second to this would be examining the effect of two different resampling approaches: <strong>(i) oversampling with Random Oversampling</strong> and <strong>(ii) undersampling with Random Undersampling</strong>, to the performance of the model.</p>
</section>
<section id="data-pre-processing" class="level1">
<h1>Data Pre-processing</h1>
<p>To yield a performant model, it’s imperative for our input data to be clean. This involves pruning observations from the original data file, scaling values, and the appropriate value conversions, among other appropriate steps that may arise.</p>
<p>On a high level, what is done in this subsection are the following:</p>
<ol type="1">
<li>Loading the dataset into R studio.</li>
<li>Null checks.</li>
<li>Encoding.</li>
</ol>
<section id="loading-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-data">Loading Data</h2>
<p>In this step the <code>diabetes_prediction_dataset.csv</code> file is stored into a table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>raw_df <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"../data/diabetes_prediction_dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After this, the head and tail of the loaded dataframe was inspected to see if the file was read into the environment.</p>
<section id="head" class="level3">
<h3 class="anchored" data-anchor-id="head">Head</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   gender   age hypertension heart_disease smoking_history   bmi HbA1c_level
   &lt;char&gt; &lt;num&gt;        &lt;int&gt;         &lt;int&gt;          &lt;char&gt; &lt;num&gt;       &lt;num&gt;
1: Female    80            0             1           never 25.19         6.6
2: Female    54            0             0         No Info 27.32         6.6
3:   Male    28            0             0           never 27.32         5.7
4: Female    36            0             0         current 23.45         5.0
5:   Male    76            1             1         current 20.14         4.8
6: Female    20            0             0           never 27.32         6.6
   blood_glucose_level diabetes
                 &lt;int&gt;    &lt;int&gt;
1:                 140        0
2:                  80        0
3:                 158        0
4:                 155        0
5:                 155        0
6:                  85        0</code></pre>
</div>
</div>
</section>
<section id="tail" class="level3">
<h3 class="anchored" data-anchor-id="tail">Tail</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   gender   age hypertension heart_disease smoking_history   bmi HbA1c_level
   &lt;char&gt; &lt;num&gt;        &lt;int&gt;         &lt;int&gt;          &lt;char&gt; &lt;num&gt;       &lt;num&gt;
1: Female    36            0             0         No Info 24.60         4.8
2: Female    80            0             0         No Info 27.32         6.2
3: Female     2            0             0         No Info 17.37         6.5
4:   Male    66            0             0          former 27.83         5.7
5: Female    24            0             0           never 35.42         4.0
6: Female    57            0             0         current 22.43         6.6
   blood_glucose_level diabetes
                 &lt;int&gt;    &lt;int&gt;
1:                 145        0
2:                  90        0
3:                 100        0
4:                 155        0
5:                 100        0
6:                  90        0</code></pre>
</div>
</div>
</section>
</section>
<section id="removing-nulls" class="level2">
<h2 class="anchored" data-anchor-id="removing-nulls">Removing Nulls</h2>
<p>Before further pre-processing steps (scaling, value conversion etc.), observations that aren’t complete will be removed. Essentially rows with missing data are to be discarded from the considered dataset.</p>
<section id="counting-nulls-attribute" class="level3">
<h3 class="anchored" data-anchor-id="counting-nulls-attribute">Counting Nulls / Attribute</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "gender"              "age"                 "hypertension"       
[4] "heart_disease"       "smoking_history"     "bmi"                
[7] "HbA1c_level"         "blood_glucose_level" "diabetes"           </code></pre>
</div>
</div>
<p>From this cell it can be gathered that there are 9 attributes all in all. From the whole dataset with respect to each of these attributes, we count the amount of nulls.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>null_counts <span class="ot">&lt;-</span> raw_df[, <span class="fu">lapply</span>(.SD, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x) <span class="sc">|</span> <span class="fu">trimws</span>(x) <span class="sc">==</span> <span class="st">""</span>))]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>null_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   gender   age hypertension heart_disease smoking_history   bmi HbA1c_level
    &lt;int&gt; &lt;int&gt;        &lt;int&gt;         &lt;int&gt;           &lt;int&gt; &lt;int&gt;       &lt;int&gt;
1:      0     0            0             0               0     0           0
   blood_glucose_level diabetes
                 &lt;int&gt;    &lt;int&gt;
1:                   0        0</code></pre>
</div>
</div>
<p>The result of the previous cell shows that all rows have complete data.</p>
</section>
</section>
<section id="type-conversions" class="level2">
<h2 class="anchored" data-anchor-id="type-conversions">Type Conversions</h2>
<p>Part of data pre-processing is also ensuring that observations are stored in programmatically convenient formats. <a href="https://www.youtube.com/watch?v=C4N3_XJJ-jU">In the context of R an example of this would be storing categorical data as factors</a>.</p>
<p><code>str(raw_df)</code> can be used to inspect how these values are stored in the table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  100000 obs. of  9 variables:
 $ gender             : chr  "Female" "Female" "Male" "Female" ...
 $ age                : num  80 54 28 36 76 20 44 79 42 32 ...
 $ hypertension       : int  0 0 0 0 1 0 0 0 0 0 ...
 $ heart_disease      : int  1 0 0 0 1 0 0 0 0 0 ...
 $ smoking_history    : chr  "never" "No Info" "never" "current" ...
 $ bmi                : num  25.2 27.3 27.3 23.4 20.1 ...
 $ HbA1c_level        : num  6.6 6.6 5.7 5 4.8 6.6 6.5 5.7 4.8 5 ...
 $ blood_glucose_level: int  140 80 158 155 155 85 200 85 145 100 ...
 $ diabetes           : int  0 0 0 0 0 0 1 0 0 0 ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>The previous query showed that the following attributes: (i) gender, (ii) hypertension, (iii) heart_disease, (iv) smoking_history, and (v) diabetes, are categorical. However, the attribute smoking_history seems to have more than just 2 possible values.</p>
<p>To be sure, an inspection of all unique values in these attributes ascertains whether or not the value is binary or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>categorical_attr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender"</span>, <span class="st">"hypertension"</span>, <span class="st">"heart_disease"</span>, <span class="st">"smoking_history"</span>, <span class="st">"diabetes"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>unique_vals <span class="ot">&lt;-</span> <span class="fu">lapply</span>(raw_df[, ..categorical_attr], unique)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(unique_vals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$gender
[1] "Female" "Male"   "Other" 

$hypertension
[1] 0 1

$heart_disease
[1] 1 0

$smoking_history
[1] "never"       "No Info"     "current"     "former"      "ever"       
[6] "not current"

$diabetes
[1] 0 1</code></pre>
</div>
</div>
<p>It can be seen that the attributes: hypertension, heart_disease, and diabetes, already only have two possible values; gender and smoking_history however do not.</p>
<section id="handling-gender-attribute" class="level3">
<h3 class="anchored" data-anchor-id="handling-gender-attribute">Handling <code>gender</code> Attribute</h3>
<p>Surface level research shows that individuals with non-binary gender identities show higher incidence rates for other diabetes related comorbidities, e.g.&nbsp;smoking <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC8529476/#:~:text=Transgender%20and%20gender%2Dexpansive%20(TGE)%20adults%E2%80%94individuals%20who%20have,to%20smoke%20cigarettes%20than%20cisgender%20individuals%20%5B3%5D.">(Tan et. al.&nbsp;2021)</a>. This suggests that gender identities beyond just male and female may provide the model with sufficient information, along with other features, for classification.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 56%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>gender</th>
<th>description</th>
<th style="text-align: right;">encoding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Male</td>
<td>Individual whose sex is Male</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>Female</td>
<td>Individual whose sex is Female</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>Individual with non-binary gender identity</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
<p>These encodings serve only to be labels that are programmatically convenient to work with in processing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>gender_encodings <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span> <span class="ot">=</span> <span class="dv">0</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span> <span class="ot">=</span> <span class="dv">2</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>raw_df[, gender_code <span class="sc">:</span><span class="er">=</span> gender_encodings[gender]]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        gender   age hypertension heart_disease smoking_history   bmi
        &lt;char&gt; &lt;num&gt;        &lt;int&gt;         &lt;int&gt;          &lt;char&gt; &lt;num&gt;
     1: Female    80            0             1           never 25.19
     2: Female    54            0             0         No Info 27.32
     3:   Male    28            0             0           never 27.32
     4: Female    36            0             0         current 23.45
     5:   Male    76            1             1         current 20.14
    ---                                                              
 99996: Female    80            0             0         No Info 27.32
 99997: Female     2            0             0         No Info 17.37
 99998:   Male    66            0             0          former 27.83
 99999: Female    24            0             0           never 35.42
100000: Female    57            0             0         current 22.43
        HbA1c_level blood_glucose_level diabetes gender_code
              &lt;num&gt;               &lt;int&gt;    &lt;int&gt;       &lt;num&gt;
     1:         6.6                 140        0           1
     2:         6.6                  80        0           1
     3:         5.7                 158        0           0
     4:         5.0                 155        0           1
     5:         4.8                 155        0           0
    ---                                                     
 99996:         6.2                  90        0           1
 99997:         6.5                 100        0           1
 99998:         5.7                 155        0           0
 99999:         4.0                 100        0           1
100000:         6.6                  90        0           1</code></pre>
</div>
</div>
<p>It can be seen that <code>gender</code> has been successfully encoded into <code>gender_code</code>. As such, the original column can now be discarded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>raw_df[, gender <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          age hypertension heart_disease smoking_history   bmi HbA1c_level
        &lt;num&gt;        &lt;int&gt;         &lt;int&gt;          &lt;char&gt; &lt;num&gt;       &lt;num&gt;
     1:    80            0             1           never 25.19         6.6
     2:    54            0             0         No Info 27.32         6.6
     3:    28            0             0           never 27.32         5.7
     4:    36            0             0         current 23.45         5.0
     5:    76            1             1         current 20.14         4.8
    ---                                                                   
 99996:    80            0             0         No Info 27.32         6.2
 99997:     2            0             0         No Info 17.37         6.5
 99998:    66            0             0          former 27.83         5.7
 99999:    24            0             0           never 35.42         4.0
100000:    57            0             0         current 22.43         6.6
        blood_glucose_level diabetes gender_code
                      &lt;int&gt;    &lt;int&gt;       &lt;num&gt;
     1:                 140        0           1
     2:                  80        0           1
     3:                 158        0           0
     4:                 155        0           1
     5:                 155        0           0
    ---                                         
 99996:                  90        0           1
 99997:                 100        0           1
 99998:                 155        0           0
 99999:                 100        0           1
100000:                  90        0           1</code></pre>
</div>
</div>
</section>
<section id="handling-smoking_history-attribute" class="level3">
<h3 class="anchored" data-anchor-id="handling-smoking_history-attribute">Handling <code>smoking_history</code> Attribute</h3>
<p>The earlier cell that was supposed to detect and count for null values was not able to catch <code>smoking_history</code> observations marked with <code>No Info</code>. That was because the previous function looked for values stored in R as <code>NA</code> or as empty strings. Including these observations may just be <em>noise</em> for the classifier, as such observations with <code>No Info</code> in <code>smoking_history</code> are discarded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>row_count_before <span class="ot">&lt;-</span> raw_df[, .N] <span class="co"># row count before drop</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Row count before drop: "</span>, row_count_before))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Row count before drop:  100000"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>raw_df <span class="ot">&lt;-</span> raw_df[<span class="sc">!</span>(smoking_history <span class="sc">==</span> <span class="st">"No Info"</span>)]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_df<span class="sc">$</span>smoking_history)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "never"       "current"     "former"      "ever"        "not current"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>row_count_after <span class="ot">&lt;-</span> raw_df[, .N] <span class="co"># row count after drop</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Row count after drop: "</span>, row_count_after))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Row count after drop:  64184"</code></pre>
</div>
</div>
<p>To turn the remaining string values into meaningful numerical data, <strong>ordinal encoding comes to mind.</strong> Notice how the magnitude of <code>smoking_history</code> can be surmised from the current values; those who have never smoked have, by definition, smoked less than those who were former smokers. Through the same intuition, it can be said that current smokers smoke the most. Formal definitions for these terms can be obtained from <a href="https://www.cdc.gov/mmwr/volumes/72/wr/mm7210a7.htm">online medical sources</a>.</p>
<p>From this information these encodings were generated:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 56%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>smoking_history</th>
<th>description</th>
<th style="text-align: right;">encoding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>never</td>
<td>never smoked before, or has smoked less than 100 cigarettes in their lifetime</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>former</td>
<td>smoked at least 100 cigarettes in their lifetime but does not currently smoke</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>not current</td>
<td>smoked at least 100 cigarettes in their lifetime but does not currently smoke</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td>ever</td>
<td>term encompassing both current and former smokers, anyone who has smoked at least 100 cigarettes in their lifetime</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>current</td>
<td>smoked at least 100 cigarettes in their lifetime and currently smokes</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
<p>It must be noted that in the context of this project, the terms <code>former</code>, <code>ever</code>, and <code>not current</code>, were not defined in the data card. As such, operative definitions were gleaned from the CDC <em>QuickStats</em> article hyperlinked above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>smoking_encodings <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"never"</span> <span class="ot">=</span> <span class="dv">0</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"former"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"not current"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ever"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"current"</span> <span class="ot">=</span> <span class="dv">2</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>raw_df[, smoking_code <span class="sc">:</span><span class="er">=</span> smoking_encodings[smoking_history]]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         age hypertension heart_disease smoking_history   bmi HbA1c_level
       &lt;num&gt;        &lt;int&gt;         &lt;int&gt;          &lt;char&gt; &lt;num&gt;       &lt;num&gt;
    1:    80            0             1           never 25.19         6.6
    2:    28            0             0           never 27.32         5.7
    3:    36            0             0         current 23.45         5.0
    4:    76            1             1         current 20.14         4.8
    5:    20            0             0           never 27.32         6.6
   ---                                                                   
64180:    26            0             0           never 34.34         6.5
64181:    40            0             0           never 40.69         3.5
64182:    66            0             0          former 27.83         5.7
64183:    24            0             0           never 35.42         4.0
64184:    57            0             0         current 22.43         6.6
       blood_glucose_level diabetes gender_code smoking_code
                     &lt;int&gt;    &lt;int&gt;       &lt;num&gt;        &lt;num&gt;
    1:                 140        0           1            0
    2:                 158        0           0            0
    3:                 155        0           1            2
    4:                 155        0           0            2
    5:                  85        0           1            0
   ---                                                      
64180:                 160        0           1            0
64181:                 155        0           1            0
64182:                 155        0           0            1
64183:                 100        0           1            0
64184:                  90        0           1            2</code></pre>
</div>
</div>
<p>It can be seen that <code>smoking_history</code> has been encoded successfully into the column smoking_code; the old column can now be safely discarded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>raw_df[, smoking_history <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         age hypertension heart_disease   bmi HbA1c_level blood_glucose_level
       &lt;num&gt;        &lt;int&gt;         &lt;int&gt; &lt;num&gt;       &lt;num&gt;               &lt;int&gt;
    1:    80            0             1 25.19         6.6                 140
    2:    28            0             0 27.32         5.7                 158
    3:    36            0             0 23.45         5.0                 155
    4:    76            1             1 20.14         4.8                 155
    5:    20            0             0 27.32         6.6                  85
   ---                                                                       
64180:    26            0             0 34.34         6.5                 160
64181:    40            0             0 40.69         3.5                 155
64182:    66            0             0 27.83         5.7                 155
64183:    24            0             0 35.42         4.0                 100
64184:    57            0             0 22.43         6.6                  90
       diabetes gender_code smoking_code
          &lt;int&gt;       &lt;num&gt;        &lt;num&gt;
    1:        0           1            0
    2:        0           0            0
    3:        0           1            2
    4:        0           0            2
    5:        0           1            0
   ---                                  
64180:        0           1            0
64181:        0           1            0
64182:        0           0            1
64183:        0           1            0
64184:        0           1            2</code></pre>
</div>
</div>
<p>Now that the data is clean, categorical columns can now be converted to the <code>factor</code> data type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>categorical_attr2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gender_code"</span>, <span class="st">"hypertension"</span>, <span class="st">"heart_disease"</span>, <span class="st">"smoking_code"</span>, <span class="st">"diabetes"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>raw_df[, (categorical_attr2) <span class="sc">:</span><span class="er">=</span> <span class="fu">lapply</span>(.SD, as.factor), .SDcols <span class="ot">=</span> categorical_attr2]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># verify changes</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  64184 obs. of  9 variables:
 $ age                : num  80 28 36 76 20 44 42 32 53 54 ...
 $ hypertension       : Factor w/ 2 levels "0","1": 1 1 1 2 1 1 1 1 1 1 ...
 $ heart_disease      : Factor w/ 2 levels "0","1": 2 1 1 2 1 1 1 1 1 1 ...
 $ bmi                : num  25.2 27.3 23.4 20.1 27.3 ...
 $ HbA1c_level        : num  6.6 5.7 5 4.8 6.6 6.5 4.8 5 6.1 6 ...
 $ blood_glucose_level: int  140 158 155 155 85 200 145 100 85 100 ...
 $ diabetes           : Factor w/ 2 levels "0","1": 1 1 1 1 1 2 1 1 1 1 ...
 $ gender_code        : Factor w/ 3 levels "0","1","2": 2 1 2 1 2 2 1 2 2 2 ...
 $ smoking_code       : Factor w/ 3 levels "0","1","2": 1 1 3 3 1 1 1 1 1 2 ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<p>The goal in exploratory data analysis is discovering correlations and distributions across all attributes. This is important as in this project, it serves as the main guide for feature selection.</p>
<p>Excluding the target, the current cleaned table has 8 attributes of which 4 are categorical (<code>hypertension</code>, <code>heart_disease</code>, <code>gender_code</code>, and <code>smoking_code</code>) and the other 4 (<code>age</code>, <code>bmi</code>, <code>HbA1c_level</code>, <code>blood_glucose_level</code>) are continuous.</p>
<section id="analyzing-target-distribution" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-target-distribution">Analyzing Target Distribution</h2>
<p>One of the biggest hurdles in classification tasks is class imbalance in the data; when there are more observations for a certain dependent variable than others then there is a class imbalance. In the context of the project the dependent variable is the <code>diabetes</code> attribute.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(raw_df<span class="sc">$</span>diabetes)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  counts,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"Non-diabetic"</span>, <span class="st">"Diabetic"</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Target Variable Distribution"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Classification"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Observation Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Visually it can be seen that the data is <strong>greatly imbalanced</strong>.</p>
</section>
<section id="examination-of-continuous-attributes" class="level2">
<h2 class="anchored" data-anchor-id="examination-of-continuous-attributes">Examination of Continuous Attributes</h2>
<p>For this subsection we consider the continuous attributes of the dataset and how they relate to the target variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>continuous_attr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"bmi"</span>, <span class="st">"HbA1c_level"</span>, <span class="st">"blood_glucose_level"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>continuous_attr_histdata <span class="ot">&lt;-</span> raw_df[, ..continuous_attr]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (attr <span class="cf">in</span> continuous_attr) {</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hist</span>(continuous_attr_histdata[[attr]],</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Histogram of"</span>, attr),</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> attr)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlations of these continuous data attributes is shown in the correlation matrix below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(continuous_attr_histdata, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          age        bmi HbA1c_level blood_glucose_level
age                 1.0000000 0.16129432  0.11598992          0.11695472
bmi                 0.1612943 1.00000000  0.08487877          0.09484836
HbA1c_level         0.1159899 0.08487877  1.00000000          0.19441839
blood_glucose_level 0.1169547 0.09484836  0.19441839          1.00000000</code></pre>
</div>
</div>
<p>Correlation between these variables seem very weak. No strong linear relationship can be made with any of them with each other. Given that EDA serves as the primary guide of feature selection in the project, it can be inferred that these attributes are not linearly redundant. This justifies the inclusion of all of these attributes into the feature set.</p>
</section>
<section id="examination-of-categorical-attributes" class="level2">
<h2 class="anchored" data-anchor-id="examination-of-categorical-attributes">Examination of Categorical Attributes</h2>
<p>For this subsection we consider the categorical attributes of the dataset and how they relate to the target variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>categorical_attr3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"hypertension"</span>, <span class="st">"heart_disease"</span>, <span class="st">"gender_code"</span>, <span class="st">"smoking_code"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>categorical_attr_notarg <span class="ot">&lt;-</span> raw_df[, ..categorical_attr3]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (attr <span class="cf">in</span> categorical_attr3) {</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">barplot</span>(<span class="fu">table</span>(categorical_attr_notarg[[attr]]),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Distribution of"</span>, attr),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">col =</span> <span class="st">"lightgreen"</span>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For an analysis of these attributes the chi-square test for independence can be used to see <em>correlation</em> between the attribute and target.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>categorical_attr_wtarg <span class="ot">&lt;-</span> <span class="fu">c</span>(categorical_attr3, <span class="st">"diabetes"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>categorical_eda <span class="ot">&lt;-</span> raw_df[, ..categorical_attr_wtarg]</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square test: Hypertension v.s. Diabetes</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(categorical_eda<span class="sc">$</span>hypertension, categorical_eda<span class="sc">$</span>diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(categorical_eda$hypertension, categorical_eda$diabetes)
X-squared = 2370, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square test: Heart Disease v.s. Diabetes</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(categorical_eda<span class="sc">$</span>heart_disease, categorical_eda<span class="sc">$</span>diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(categorical_eda$heart_disease, categorical_eda$diabetes)
X-squared = 1844.2, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square test: Gender v.s. Diabetes</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(categorical_eda<span class="sc">$</span>gender_code, categorical_eda<span class="sc">$</span>diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(table(categorical_eda$gender_code,
categorical_eda$diabetes)): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(categorical_eda$gender_code, categorical_eda$diabetes)
X-squared = 209.99, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square test: Smoking v.s. Diabetes</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(categorical_eda<span class="sc">$</span>smoking_code, categorical_eda<span class="sc">$</span>diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(categorical_eda$smoking_code, categorical_eda$diabetes)
X-squared = 253.13, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>All p-values obtained are very small (p &lt; 2.2e-16) which provides strong evidence to reject the null-hypothesis. For the attributes <code>hypertension</code>, <code>heart_disease</code>, and <code>smoking_code</code> this is to be expected since they are known comorbidities for many diseases. However, <code>gender_code</code> also yielding low p-values suggests that gender (not sex, since non-binary identites are included) is statistically significant when analyzing diabetes distribution.</p>
<p>All that being said, failure to reject the null hypothesis for any of the variables suggests that they should be included to the final feature set.</p>
</section>
</section>
<section id="modeling" class="level1">
<h1>Modeling</h1>
<p>From EDA, through the use of correlation matrix and Chi-square tests, the final feature set was obtained. Continuous variables were not colinear with each other and all categorical variables yielded small p-values, as such all nine features from the base dataset is used in modeling.</p>
<p>In this section logistic regression is run three times: (i) without resampling, (ii) resampling with ROS, and (iii) resampling with RUS. The target data distribution is heavily imbalanced, making the dataset a good candidate for analyzing performance contributions/effects of resampling techniques.</p>
<section id="scaling-continuous-attributes" class="level2">
<h2 class="anchored" data-anchor-id="scaling-continuous-attributes">Scaling Continuous Attributes</h2>
<p>https://www.geeksforgeeks.org/logistic-regression-and-the-feature-scaling-ensemble/</p>
<p>An inspection of the data’s continuous attributes (e.g.&nbsp;<code>age</code>, <code>bmi</code>, <code>blood_glucose_level</code>) makes apparent the difference in <em>scale</em> that these values have. From a numerical standpoint, measurements in <code>bmi</code> and <code>age</code> are significantly less than measurements in <code>blood_glucose_level</code>.</p>
<p>Feature scaling ensures that all features contribute equally to the model’s learning process. Numerically large features, when not scaled properly, may dominate learning over smaller-scale features; <code>blood_glucose_level</code> may, by virtue of the units it’s measured in, overtake <code>HbA1c_level</code> in contribution because of the difference in their values.</p>
<p><code>scale</code> performs z-score scaling, centering values around 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>raw_df<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">scale</span>(raw_df<span class="sc">$</span>age)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>raw_df<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">scale</span>(raw_df<span class="sc">$</span>bmi)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>raw_df<span class="sc">$</span>HbA1c_level <span class="ot">&lt;-</span> <span class="fu">scale</span>(raw_df<span class="sc">$</span>HbA1c_level)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>raw_df<span class="sc">$</span>blood_glucose_level <span class="ot">&lt;-</span> <span class="fu">scale</span>(raw_df<span class="sc">$</span>blood_glucose_level)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(raw_df[, ..continuous_attr])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          age        bmi HbA1c_level blood_glucose_level
        &lt;num&gt;      &lt;num&gt;       &lt;num&gt;               &lt;num&gt;
1:  1.7121451 -0.4963200   0.9454139         0.008816956
2: -0.9490171 -0.1694423   0.1238857         0.435702151
3: -0.5396076 -0.7633468  -0.5150807         0.364554618
4:  1.5074403 -1.2713117  -0.6976425         0.364554618
5: -1.3584267 -0.1694423   0.9454139        -1.295554474
6: -0.1301980 -1.3986865   0.8541330         1.431767606</code></pre>
</div>
</div>
</section>
<section id="logistic-regression-without-resampling" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-without-resampling">Logistic Regression without Resampling</h2>
<p>In this subsection, logistic regression is performed and evaluated for accuracy without resampling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>for_baseline <span class="ot">&lt;-</span> <span class="fu">copy</span>(raw_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="train-test-set-creation" class="level3">
<h3 class="anchored" data-anchor-id="train-test-set-creation">Train &amp; Test Set Creation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="st">"123"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># there are 60k rows so let's try 80-20</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>split_baseline <span class="ot">&lt;-</span> caTools<span class="sc">::</span><span class="fu">sample.split</span>(for_baseline<span class="sc">$</span>diabetes, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>baseline_train_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_baseline, split_baseline <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>baseline_test_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_baseline, split_baseline <span class="sc">==</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-training" class="level3">
<h3 class="anchored" data-anchor-id="model-training">Model Training</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>baseline_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> .,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> baseline_train_data,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> binomial)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(baseline_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ ., family = binomial, data = baseline_train_data)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          -4.56196    0.06150 -74.176  &lt; 2e-16 ***
age                   0.92721    0.02885  32.143  &lt; 2e-16 ***
hypertension1         0.72621    0.05672  12.804  &lt; 2e-16 ***
heart_disease1        0.72911    0.07595   9.600  &lt; 2e-16 ***
bmi                   0.56807    0.02055  27.638  &lt; 2e-16 ***
HbA1c_level           2.52982    0.04873  51.913  &lt; 2e-16 ***
blood_glucose_level   1.37864    0.02535  54.389  &lt; 2e-16 ***
gender_code1         -0.29150    0.04507  -6.468 9.92e-11 ***
gender_code2         -7.82022  103.65242  -0.075    0.940    
smoking_code1         0.02267    0.04891   0.463    0.643    
smoking_code2         0.14949    0.06802   2.198    0.028 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 35538  on 51346  degrees of freedom
Residual deviance: 14314  on 51336  degrees of freedom
AIC: 14336

Number of Fisher Scoring iterations: 11</code></pre>
</div>
</div>
</section>
<section id="making-predictions-on-baseline_test_data" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions-on-baseline_test_data">Making Predictions on <code>baseline_test_data</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>baseline_test_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(baseline_model,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">newdata =</span> baseline_test_data,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>baseline_test_pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(baseline_test_probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="co"># report accuracy</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(baseline_test_pred <span class="sc">==</span> baseline_test_data<span class="sc">$</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9498325</code></pre>
</div>
</div>
<p>Without any resampling, the probability of an accurate prediction is 94.9%? That’s higher than most people’s final grade in CSCI 21! Recall that the target distribution is greatly imbalanced, this is may be a case of the <em>accuracy paradox</em> where the model correctly makes predictions on the majority class and neglects the minority class.</p>
</section>
<section id="confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrix">Confusion Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>baseline_confmatrix <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(baseline_test_data<span class="sc">$</span>diabetes),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(baseline_test_pred)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(baseline_confmatrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 11284   144
         1   500   909
                                          
               Accuracy : 0.9498          
                 95% CI : (0.9459, 0.9535)
    No Information Rate : 0.918           
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.7113          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9576          
            Specificity : 0.8632          
         Pos Pred Value : 0.9874          
         Neg Pred Value : 0.6451          
             Prevalence : 0.9180          
         Detection Rate : 0.8790          
   Detection Prevalence : 0.8902          
      Balanced Accuracy : 0.9104          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>The confusion matrix sheds more light on the model’s performance. For cases where the model is tested on diabetic data (the correct prediction is 1), the model does not perform so well. In the second line of the confusion matrix the ratio between false positives and true positives is 500:909.</p>
<p>PPV and NPV values make more apparent the <em>accuracy paradox</em>. The PPV being 98.7% means that when the model makes a 0 prediction (non-diabetic), it is correct 98.7% of the time. In contrast, the NPV being 64.5% means that when the model predicts a 1 prediction (diabetic), it is only correct 64.5% of the time. <strong>Given the class imbalance, the model will still get a high accuracy mark if it just predicted all observations to be non-diabetic.</strong></p>
</section>
</section>
<section id="logistic-regression-with-resampling" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-with-resampling">Logistic Regression with Resampling</h2>
<p>The previous subsection showed room for improvement with the NPV of the model. One of the main challenges in classification tasks is deciding how to handle class imbalances, one of the ways this is addressed is through resampling. Resampling, makes it so that the proportions in the training data is more balanced, giving the model more exposure to both targets.</p>
<p>The resampling approaches used in this project are: <strong>(i) Oversampling with ROS, and (ii) Undersampling with RUS</strong>.</p>
<section id="train-test-set-creation-for-ros" class="level3">
<h3 class="anchored" data-anchor-id="train-test-set-creation-for-ros">Train &amp; Test Set Creation for ROS</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>for_ROS <span class="ot">&lt;-</span> <span class="fu">copy</span>(raw_df)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="st">"123"</span>)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>split_ROS <span class="ot">&lt;-</span> caTools<span class="sc">::</span><span class="fu">sample.split</span>(for_ROS<span class="sc">$</span>diabetes, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>ROS_train_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_ROS, split_ROS <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>ROS_test_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_ROS, split_ROS <span class="sc">==</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ros-resampling" class="level3">
<h3 class="anchored" data-anchor-id="ros-resampling">ROS Resampling</h3>
<p>ROS works by randomly duplicating rows of the minority class, adding these dupes up until both classes have roughly the same number of instances. As such, plotting the training data before and after resampling shows the effect of ROS on the observed class imbalance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>ROS_targcounts <span class="ot">&lt;-</span> <span class="fu">table</span>(ROS_train_data<span class="sc">$</span>diabetes)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  ROS_targcounts,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"Non-diabetic"</span>, <span class="st">"Diabetic"</span>),</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Target Variable Distribution Before ROS"</span>,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Classification"</span>,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Observation Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution in the bar graph mirrors the one shown in EDA previously.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>ROS_targcounts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
45710  5637 </code></pre>
</div>
</div>
<p>Getting an approximate ratio…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>targ_ratio <span class="ot">&lt;-</span> <span class="dv">45710</span> <span class="sc">/</span> <span class="dv">5637</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>targ_ratio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.108923</code></pre>
</div>
</div>
<p>The majority class outnumbers the minority class by about 8 to 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>ROS_output <span class="ot">&lt;-</span> ROSE<span class="sc">::</span><span class="fu">ovun.sample</span>(</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  diabetes <span class="sc">~</span> .,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ROS_train_data,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"over"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">max</span>(<span class="fu">table</span>(ROS_train_data<span class="sc">$</span>diabetes))</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>ROS_train_data <span class="ot">&lt;-</span> ROS_output<span class="sc">$</span>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new target distribution is…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ROS_targcounts2 <span class="ot">&lt;-</span> <span class="fu">table</span>(ROS_train_data<span class="sc">$</span>diabetes)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  ROS_targcounts2,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"Non-diabetic"</span>, <span class="st">"Diabetic"</span>),</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Target Variable Distribution After ROS"</span>,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Classification"</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Observation Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-training-on-ros-data" class="level3">
<h3 class="anchored" data-anchor-id="model-training-on-ros-data">Model Training on ROS Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ROS_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> .,</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ROS_train_data,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> binomial)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ROS_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ ., family = binomial, data = ROS_train_data)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -2.39419    0.02835 -84.438  &lt; 2e-16 ***
age                  0.99691    0.01464  68.118  &lt; 2e-16 ***
hypertension1        0.77684    0.03194  24.318  &lt; 2e-16 ***
heart_disease1       0.85023    0.04430  19.192  &lt; 2e-16 ***
bmi                  0.61553    0.01162  52.976  &lt; 2e-16 ***
HbA1c_level          2.36961    0.02458  96.392  &lt; 2e-16 ***
blood_glucose_level  1.31152    0.01462  89.686  &lt; 2e-16 ***
gender_code1        -0.29364    0.02359 -12.448  &lt; 2e-16 ***
gender_code2        -8.88877   61.74552  -0.144    0.886    
smoking_code1        0.03809    0.02576   1.479    0.139    
smoking_code2        0.15515    0.03491   4.444 8.81e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 126735  on 91419  degrees of freedom
Residual deviance:  47775  on 91409  degrees of freedom
AIC: 47797

Number of Fisher Scoring iterations: 10</code></pre>
</div>
</div>
</section>
<section id="making-predictions-on-ros_test_data" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions-on-ros_test_data">Making Predictions on <code>ROS_test_data</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ROS_test_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(ROS_model,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">newdata =</span> ROS_test_data,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>ROS_test_pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(ROS_test_probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ROS_test_pred <span class="sc">==</span> ROS_test_data<span class="sc">$</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8812807</code></pre>
</div>
</div>
<p>So from a very comfortable A, accuracy has dropped to an almost borderline B+. Have the other performance metrics improved?</p>
</section>
<section id="ros-model-confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="ros-model-confusion-matrix">ROS Model Confusion Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>ROS_confmatrix <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(ROS_test_data<span class="sc">$</span>diabetes),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(ROS_test_pred)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>ROS_confmatrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 10079  1349
         1   175  1234
                                          
               Accuracy : 0.8813          
                 95% CI : (0.8756, 0.8868)
    No Information Rate : 0.7988          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.555           
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9829          
            Specificity : 0.4777          
         Pos Pred Value : 0.8820          
         Neg Pred Value : 0.8758          
             Prevalence : 0.7988          
         Detection Rate : 0.7852          
   Detection Prevalence : 0.8902          
      Balanced Accuracy : 0.7303          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>As expected, there is an increase in the value of NPV. Now that the training data has been resampled appropriately to make diabetic and non-diabetic instances as frequent, the model’s increased exposure to diabetic data, despite <em>just being duplicates</em>, affects the learning process of the model. <strong>Is this the best way to train the model though?</strong></p>
</section>
<section id="train-test-set-creation-for-rus" class="level3">
<h3 class="anchored" data-anchor-id="train-test-set-creation-for-rus">Train &amp; Test Set Creation for RUS</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>for_RUS <span class="ot">&lt;-</span> <span class="fu">copy</span>(raw_df)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="st">"123"</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>split_RUS <span class="ot">&lt;-</span> caTools<span class="sc">::</span><span class="fu">sample.split</span>(for_RUS<span class="sc">$</span>diabetes, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>RUS_train_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_RUS, split_RUS <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>RUS_test_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(for_RUS, split_RUS <span class="sc">==</span> <span class="cn">FALSE</span>)</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>RUS_train_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              age hypertension heart_disease        bmi HbA1c_level
            &lt;num&gt;       &lt;fctr&gt;        &lt;fctr&gt;      &lt;num&gt;       &lt;num&gt;
    1:  1.7121451            0             1 -0.4963200   0.9454139
    2: -0.9490171            0             0 -0.1694423   0.1238857
    3: -0.5396076            0             0 -0.7633468  -0.5150807
    4: -0.1301980            0             0 -1.3986865   0.8541330
    5: -0.2325504            0             0  0.8004482  -0.6976425
   ---                                                             
51343: -1.2048981            0             0 -1.6196742   0.2151666
51344: -1.2560743            0             0  0.1881281   0.3977284
51345: -0.3349028            0             0  1.8823672  -1.8842944
51346: -1.1537219            0             0  1.0736136  -1.4278898
51347:  0.5350926            0             0 -0.9198798   0.9454139
       blood_glucose_level diabetes gender_code smoking_code
                     &lt;num&gt;   &lt;fctr&gt;      &lt;fctr&gt;       &lt;fctr&gt;
    1:         0.008816956        0           1            0
    2:         0.435702151        0           0            0
    3:         0.364554618        0           1            2
    4:         1.431767606        1           1            0
    5:         0.127396176        0           0            0
   ---                                                      
51343:        -0.939816812        0           1            0
51344:        -1.414133695        0           0            2
51345:         0.364554618        0           1            0
51346:        -0.939816812        0           1            0
51347:        -1.176975254        0           1            2</code></pre>
</div>
</div>
</section>
<section id="rus-resampling" class="level3">
<h3 class="anchored" data-anchor-id="rus-resampling">RUS Resampling</h3>
<p>RUS works in the <em>opposite direction</em> of ROS; whereas previously the minority class was duplicated to match the count of the majority class, here random rows from the majority class is removed to match the count of the minority class. The result is a smaller dataset with fewer total samples.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>RUS_targcounts <span class="ot">&lt;-</span> <span class="fu">table</span>(RUS_train_data<span class="sc">$</span>diabetes)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  RUS_targcounts,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"Non-diabetic"</span>, <span class="st">"Diabetic"</span>),</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Target Variable Distribution Before RUS"</span>,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Classification"</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Observation Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The majority class outnumbers the minority class by about the same proportions again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>RUS_output <span class="ot">&lt;-</span> ROSE<span class="sc">::</span><span class="fu">ovun.sample</span>(</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  diabetes <span class="sc">~</span> .,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> RUS_train_data,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"under"</span>,</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">min</span>(<span class="fu">table</span>(RUS_train_data<span class="sc">$</span>diabetes))</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>RUS_train_data <span class="ot">&lt;-</span> RUS_output<span class="sc">$</span>data</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(RUS_train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         age hypertension heart_disease         bmi HbA1c_level
1 -0.5396076            0             0 -0.40424179  -0.6976425
2 -0.8978409            0             0  0.33238394  -0.6976425
3 -0.4884314            0             0 -0.16944234   0.8541330
4  0.7909736            0             0  0.17585097   0.4890094
5  1.1492070            0             0  0.05768393   0.5802903
6  1.7121451            0             0 -1.53680385  -1.8842944
  blood_glucose_level diabetes gender_code smoking_code
1        -1.414133695        0           1            0
2         0.127396176        0           1            0
3         0.459417995        0           0            0
4        -0.228341486        0           0            2
5         0.008816956        0           0            1
6         0.483133839        0           1            1</code></pre>
</div>
</div>
<p>How does the distribution change after resampling?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>RUS_targcounts2 <span class="ot">&lt;-</span> <span class="fu">table</span>(RUS_train_data<span class="sc">$</span>diabetes)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  RUS_targcounts2,</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"Non-diabetic"</span>, <span class="st">"Diabetic"</span>),</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Target Variable Distribution After RUS"</span>,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Classification"</span>,</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Observation Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now that the training set has been balanced, it’s time to train the model.</p>
</section>
<section id="model-training-on-rus-data" class="level3">
<h3 class="anchored" data-anchor-id="model-training-on-rus-data">Model Training on RUS Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>RUS_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> .,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> RUS_train_data,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> binomial)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RUS_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ ., family = binomial, data = RUS_train_data)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          -2.36201    0.07837 -30.140  &lt; 2e-16 ***
age                   0.94846    0.04074  23.283  &lt; 2e-16 ***
hypertension1         0.85241    0.09053   9.416  &lt; 2e-16 ***
heart_disease1        0.71612    0.12293   5.825 5.69e-09 ***
bmi                   0.56312    0.03210  17.542  &lt; 2e-16 ***
HbA1c_level           2.33316    0.06779  34.416  &lt; 2e-16 ***
blood_glucose_level   1.30293    0.04093  31.830  &lt; 2e-16 ***
gender_code1         -0.29158    0.06610  -4.411 1.03e-05 ***
gender_code2         -8.78195  196.96771  -0.045    0.964    
smoking_code1         0.03484    0.07219   0.483    0.629    
smoking_code2         0.13265    0.09840   1.348    0.178    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 15629  on 11273  degrees of freedom
Residual deviance:  6056  on 11263  degrees of freedom
AIC: 6078

Number of Fisher Scoring iterations: 10</code></pre>
</div>
</div>
</section>
<section id="making-predictions-on-rus_test_data" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions-on-rus_test_data">Making Predictions on <code>RUS_test_data</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>RUS_test_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(RUS_model,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">newdata =</span> RUS_test_data,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>RUS_test_pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(RUS_test_probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(RUS_test_pred <span class="sc">==</span> RUS_test_data<span class="sc">$</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8829945</code></pre>
</div>
</div>
<p>Accuracy is about the same as the ROS model. Are there any improvements for the other model performance metrics?</p>
</section>
<section id="rus-model-confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="rus-model-confusion-matrix">RUS Model Confusion Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>RUS_confmatrix <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(RUS_test_data<span class="sc">$</span>diabetes),</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.factor</span>(RUS_test_pred)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>RUS_confmatrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 10105  1323
         1   179  1230
                                          
               Accuracy : 0.883           
                 95% CI : (0.8773, 0.8885)
    No Information Rate : 0.8011          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.5584          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9826          
            Specificity : 0.4818          
         Pos Pred Value : 0.8842          
         Neg Pred Value : 0.8730          
             Prevalence : 0.8011          
         Detection Rate : 0.7872          
   Detection Prevalence : 0.8902          
      Balanced Accuracy : 0.7322          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>NPV and PPV seem to be about the same as their ROS counterparts.</p>
</section>
</section>
</section>
<section id="results-discussion" class="level1">
<h1>Results &amp; Discussion</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show barplot ekekekek</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this project a binary classification task was performed on a public health dataset containing a total of 9 features. A binary target <code>diabetes</code> was chosen to be the target of the binary classification task. Predictors consisted of 4 categorical and 4 continuous variables, all of which through EDA, were shown to be statistically significant with regards to the target variable (continuous attributes were not colinear, categorical attributes all yielded small p-values). The main challenge in performing this task was in accounting for the class imbalance of the target in the dataset, for every instance of the minority class there were about 8 of the majority class. The majority class consisted of non-diabetic observations.</p>
<p>Modeling was done through logistic regression, this was performed three times to see the effect of different resampling approaches: (i) no resampling, (ii) random oversampling, and (iii) random undersampling. The first iteration of modeling yielded the highest accuracy metric of 94.9%, for each prediction the model made on its test set the likelihood of it being correct was 94.9%. A deeper analysis of its performance however showed that while PPV is high, NPV was only 64.5%-the model fails to predict cases where an observation should be diabetic. Given the distribution of the target, if the model predicted non-diabetic for all observations, the accuracy would still be in the 90s.</p>
<p>The next two iterations of modeling applied either RUS or ROS to their training data to remove the class imbalance of the target. In ROS, random minority observations were duplicated until target frequencies balanced out. RUS on the other hand randomly removed instances of the majority class until the target frequencies balanced out. Both models performed similarly on their test sets, a loss of about 7% to accuracy but an increase to 88% in NPV. While these models trained on resampled data only get accurate predictions approximately 88% of the time, they’re able to predict the diabetic case 88% of the time also-a stark increase from the non-resampled’s NPV of 64.5%. Whether or not this is the case that defines the metric for model sensitivity requires input from domain experts.</p>
<p>This project was primarily inspired by the study done by <a href="https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-023-10418-6">Deina et. al.&nbsp;(2024)</a>. It’s a paper that proposed a ML framework for data preparation and model training alongside introducing a novel resampling technique, Instance Hardness Threshold (IHT), and model, Symbolic Regression (SR), to predict medical appointment no-shows. The paper compared performances of KNN, SVM, and SR models alongside different sampling techniques such as RUS, SMOTE, NearMiss - 1, and IHT. Through iterations of cross-validation they found that the combination of SR &amp; IHT outperformed almost every other combination for most performance metrics.</p>
<p>This project’s methodology initially was to compare a suite of oversampling and undersampling techniques to the performance of a KNN model and a logistic regression model. However due to limitations in compute power, made apparent in an attempt to do SMOTE, the project was downsized to just a comparison of no-resampling, ROS, and RUS when paired with logistic regression. Despite this, the project still demonstrates the benefits of resampling especially when dealing with highly imbalanced datasets. Further iterations of this project may look into improving the EDA/feature engineering/feature extraction along with using more models.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Excluding the dataset, here is a list of the resources that were consulted in the making of this project:</p>
<p>https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-023-10418-6</p>
<p>https://www.geeksforgeeks.org/confusion-matrix-in-r/</p>
<p>https://rpubs.com/SameerMathur/LR_GLM_CCDefault</p>
<p>https://www.youtube.com/watch?v=C4N3_XJJ-jU</p>
<p>https://pmc.ncbi.nlm.nih.gov/articles/PMC8529476/#:~:text=Transgender%20and%20gender%2Dexpansive%20(TGE)%20adults%E2%80%94individuals%20who%20have,to%20smoke%20cigarettes%20than%20cisgender%20individuals%20[3].</p>
<p>https://www.cdc.gov/mmwr/volumes/72/wr/mm7210a7.htm</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>